### ISSUE TITLE
Broken Download Link

### ISSUE THREAD

**Issue by code856** [MAXBURAOT/SmartSteamEmu#12]
The download link for SSE is broken. Could the creator fix this?

**Comment by Adaliciously** [comment]
I can try compiling it myself...

**Comment by Adaliciously** [comment]
[Release.zip](https://github.com/MAXBURAOT/SmartSteamEmu/files/4413185/Release.zip)
here

**Comment by Adaliciously** [comment]
Though, to find some of the .ini files required you'll have to visit a certain site
