### ISSUE TITLE
Need linux version

### ISSUE THREAD

**Issue by JoneKone** [MAXBURAOT/SmartSteamEmu#7]
maybe.. one day somebody will bother to make linux version of this..

**Comment by mirh** [comment]
This already can do it for many use cases
https://gitlab.com/Mr_Goldberg/goldberg_emulator

**Comment by DraconicNEO** [comment]
> This already can do it for many use cases https://gitlab.com/Mr_Goldberg/goldberg_emulator

I don't think this one will work for games which use Steam DRM

```
It doesn't break any DRM. If the game has a protection that doesn't let you use a custom steam api dll it needs to be cracked before you use my emulator. Steam is a DRM as much as any API is a DRM. Steam has actual DRM called steamstub which can easily be cracked but this won't crack it for you.
```
AFAIK Goldberg seems to respect Steam DRM and doesn't bypass it like this app does.
